/* GENERATED by tools/vendor_wamr.py -- the fork commit the vendored
 * runtime in wamr/ was copied from (wamr_vendor.json). The provenance
 * check compares a module's key against it. Do not edit. */
#ifndef MOY_WASM_PIN_H
#define MOY_WASM_PIN_H
#define MOY_WASM_FORK_COMMIT "a7b71791f0e7b36e34d7d8abaef57b1d64d6f8e7"
#endif
