/* GENERATED by tools/vendor_wamr.py -- the fork commit the vendored
 * runtime in wamr/ was copied from (wamr_vendor.json). The provenance
 * check compares a module's key against it. Do not edit. */
#ifndef MOY_WASM_PIN_H
#define MOY_WASM_PIN_H
#define MOY_WASM_FORK_COMMIT "f4decc3b7f2576a6aaabd2e0afbfa39b64156cdb"
#endif
