/* GENERATED by tools/vendor_wamr.py -- the fork commit the vendored
 * runtime in wamr/ was copied from (wamr_vendor.json). The provenance
 * check compares a module's key against it. Do not edit. */
#ifndef MOY_WASM_PIN_H
#define MOY_WASM_PIN_H
#define MOY_WASM_FORK_COMMIT "a03cce7e8ceb08a22e2527a9a9e69b0197459369"
#endif
