#pragma once

#define KIDCODE_BOARD_ID "lilygo_t_deck_plus"
#define KIDCODE_BOARD_TITLE "LilyGO T-Deck Plus"

#define KIDCODE_BOARD_POWERON 10
#define KIDCODE_BOARD_I2C_SDA 18
#define KIDCODE_BOARD_I2C_SCL 8
#define KIDCODE_BOARD_KEYBOARD_ADDR 0x55
#define KIDCODE_BOARD_KEYBOARD_INT 46
#define KIDCODE_BOARD_SDCARD_CS 39
#define KIDCODE_BOARD_TFT_CS 12
#define KIDCODE_BOARD_TFT_DC 11
#define KIDCODE_BOARD_TFT_BACKLIGHT 42
#define KIDCODE_BOARD_SPI_MOSI 41
#define KIDCODE_BOARD_SPI_MISO 38
#define KIDCODE_BOARD_SPI_SCK 40
#define KIDCODE_BOARD_GPS_TX_PIN 43
#define KIDCODE_BOARD_GPS_RX_PIN 44
#define KIDCODE_BOARD_BOOT_PIN 0
