"""The SYSTEM APP registry -- AUTO-GENERATED by tools/gen_device_carts.py
from the `app` blocks in system_carts/*/manifest.json.

Do NOT edit: regenerate with

    python tools/gen_device_carts.py --app-decls

and tests/test_app_registry.py fails until you do.

This is the frozen tiers' copy of the declaration. The manifests are the
source of truth, but a board and the wasm head have no `system_carts/` to
read -- exactly as `carts_data.py` is the frozen copy of the cart bodies.
console.py loops over APPS to import, construct and register every system
app; there is no per-app line anywhere in the shell.

  id         the process kind (router / back-stack / window key)
  entry      "module:Class" -- a runtime/ module staged to every target
  text_mode  True = a TYPING app (clean ASCII keyboard, Writer precedent)
  order      registration precedence (NOT the cart's shelf order)
  folder     the identity cart it rides on, in system_carts/
  title      that cart's title (what the device names its seeded folder from)
  min_size   optional (w, h) windowed resize floor; omitted means the app's
             layout MIN_W/MIN_H are adopted at registration
"""

APPS = [
    {'id': 'artwork', 'entry': 'artwork:PaintAppLayer', 'text_mode': False, 'order': 10, 'folder': 'paint', 'title': 'Paint'},
    {'id': 'appearance', 'entry': 'appearance_app:AppearanceAppLayer', 'text_mode': False, 'order': 20, 'folder': 'theme_picker', 'title': 'Appearance'},
    {'id': 'writer', 'entry': 'writer_app:WriterAppLayer', 'text_mode': True, 'order': 30, 'folder': 'writer', 'title': 'Writer'},
    {'id': 'storybook', 'entry': 'storybook_app:StorybookAppLayer', 'text_mode': False, 'order': 40, 'folder': 'storybook', 'title': 'Storybook'},
    {'id': 'sheets', 'entry': 'sheets_app:SheetsAppLayer', 'text_mode': True, 'order': 50, 'folder': 'sheets', 'title': 'Sheets'},
    {'id': 'files', 'entry': 'files_app:FilesAppLayer', 'text_mode': True, 'order': 60, 'folder': 'files', 'title': 'Files'},
    {'id': 'calc', 'entry': 'calc_app:CalcAppLayer', 'text_mode': False, 'order': 70, 'folder': 'calc', 'title': 'Calc'},
]
