# Unix-port user-module glue: moy_web is VM-neutral C (py/obj.h + py/runtime.h
# plus one generated table), so it also builds into ports/unix -- which is how
# the baked bundle can be opened without a board.
#
# This must stay the twin of micropython.cmake. When six verbs became calls into
# vendored libmoy, moy_gfx's cmake gained the sources and its .mk did not, the
# unix port stopped linking, and nothing caught it (the firmware tests grep
# frozen source rather than compile it).
#
# moy_web_blob.gen.c is GENERATED by tools/gen_web_blob.py and gitignored. Both
# boards' build.sh run the generator before staging; a unix build that adds
# moy_web to UNIX_MP_MODULES must run it too, or make stops on a missing file.

MOY_WEB_MOD_DIR := $(USERMOD_DIR)

SRC_USERMOD += $(MOY_WEB_MOD_DIR)/modmoy_web.c
SRC_USERMOD += $(MOY_WEB_MOD_DIR)/moy_web_blob.gen.c

CFLAGS_USERMOD += -I$(MOY_WEB_MOD_DIR)
