#!/usr/bin/env python3
"""The PICO-8 corpus as ONE cart each, with the measured start behind a config toggle.

    python3 tools/gen_p8_ports.py                 # all of them, into ports/p8/
    python3 tools/gen_p8_ports.py mossmoss-17     # just these lids
    python3 tools/gen_p8_ports.py --dest /tmp/x   # somewhere else

WHY ONE CART AND NOT TWO. The corpus is two things at once: the COMPATIBILITY
set (does the importer handle this cart -- does it boot, take input, draw right)
and the PERFORMANCE set (what does a frame cost with a real scene on screen).
Those wanted different starts, so the boards grew a plain import AND a "… Perf"
twin of each, and the two drifted: by 2026-09-11 every Perf cart in `ports/p8perf`
carried `P8_VH = 128` while a fresh import carries 120, so every perf number was
measured on a viewport 8 rows taller than the one a real cart draws -- and no
two boards held the same set. One cart with a toggle cannot drift from itself.

THE TOGGLE IS `config.json`'s `perf`, which is the cart API's existing
"Make it mine" surface (`cfg(key, default)`, docs/moy_cart_api.md): 0 plays the
cart normally, 1 jumps straight into the measured scene. A kid never sees it; a
measurement session flips it in the Editor's Config tab with no re-push, and
`host_app._SEED_PRESERVE` keeps the value across a re-seed. 0/1 rather than
true/false because that is what the shipped carts already use
(`brick_siege_lua.moy/config.json`) and what `cfg` types cleanly -- moy_lua.c's
`l_cfg` converts a whole-string number to a Lua number, so `cfg("perf", 0) ~= 0`
is the guard on every tier.

THE CARTS ARE NOT IN THIS REPO and must not be: they are their authors' work,
several under licences that forbid redistribution (ports/README.md). What IS
committed is the recipe -- `ports/p8/perf/<lid>.lua`, our own ~10 lines per cart
naming the scene to start in and why. The cart bytes come from moy-spec's
`conformance/p8_corpus.json` links, cached by its `fetch_p8_corpus.py` in
~/.cache/moy/p8, which is what moy-spec CI already does.
"""

import json
import os
import sys

_THIS = os.path.dirname(os.path.abspath(__file__))
if _THIS not in sys.path:
    sys.path.insert(0, _THIS)

from import_p8 import import_p8                                # noqa: E402
import p8_lua_port                                             # noqa: E402

ROOT = os.path.dirname(_THIS)
PERF_DIR = os.path.join(ROOT, "ports", "p8", "perf")
DEST = os.path.join(ROOT, "ports", "p8")
CORPUS_DIR = os.path.join(os.path.expanduser("~"), ".cache", "moy", "p8")

# The wrapper's own file, listed AFTER main.lua in the manifest's `sources`
# (SPEC.md 4). Two reasons it is a file and not an appendix: it wraps what the
# cart DEFINED (`p8_init`), so it cannot run before main.lua; and it is OURS,
# so it has no business inside the one file a person opens to read the game.
#
# It reaches the cart's state through GLOBALS, which is the only thing that
# crosses a chunk boundary -- which is fine, because a p8 cart's top-level
# names are globals by construction (p8 Lua has no module scope to hide them
# in). A snippet that needed one of main.lua's own `local`s would fail at
# generate time, loudly, rather than read a nil.
GUARD_HEAD = """-- PERF (generated by tools/gen_p8_ports.py from ports/p8/perf/%s.lua).
--
-- config.json's `perf`: 0 plays this cart from its own title screen, 1 starts
-- it in the scene the perf ledger (#66) measures. Everything below runs only
-- under 1, and touches nothing when it is 0.
if cfg("perf", 0) ~= 0 then
"""
GUARD_TAIL = "end\n"

PERF_NAME = "perf.lua"



def _list_source(out_dir, name):
    """Append `name` to the cart's `sources` (SPEC.md 4), after main.

    Rewritten through the importer's own `manifest_text` so a regenerated cart
    and a freshly imported one differ by the added line and nothing else -- a
    json.dump here would reorder every field and reflow the palette."""
    path = os.path.join(out_dir, "manifest.json")
    with open(path, "r", encoding="utf-8") as f:
        man = json.load(f)
    names = list(man.get("sources") or [man.get("main", "main.lua")])
    if name not in names:
        names.append(name)
    man["sources"] = names
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(p8_lua_port.manifest_text(man))


def _indent(body):
    """The snippet, one level in -- it is inside an `if` now."""
    out = []
    for line in body.splitlines():
        out.append(("  " + line) if line.strip() else line)
    return "\n".join(out).rstrip("\n") + "\n"


# The carts the fleet carries. A lid with a `ports/p8/perf/<lid>.lua` snippet
# gets the toggle; one without is COMPATIBILITY-ONLY and still belongs here --
# celeste2 is the importer's own "refused" verdict, which is a thing the boards
# must keep being able to reproduce. The three corpus lids that do not import at
# all (nimudazus, poom, terra) are deliberately absent: moy-spec's `p8-carts`
# gate is where those are watched, not a board's shelf.
CORPUS = (
    "42930", "bunnysurvivor-9", "celeste_classic_2-5", "crimson_night-5",
    "dank_tomb-0", "deepdark-1", "dungeons_and_diagrams-5", "giftguardian-5",
    "loop-4", "lowmemsky-1", "mossmoss-17", "petal_quest-12", "picooffroad-5",
)


def build(lid, corpus=CORPUS_DIR, dest=DEST):
    """One `<dest>/<lid>.moy` from the cached cart + this lid's perf snippet,
    if it has one."""
    src = os.path.join(corpus, lid + ".p8.png")
    if not os.path.isfile(src):
        raise SystemExit(
            "no cached cart for %s at %s -- fetch the corpus first:\n"
            "  python3 ../moy-spec/conformance/fetch_p8_corpus.py" % (lid, src))
    out_dir = os.path.join(dest, lid + ".moy")
    summary = import_p8(src, out_dir)
    # The importer already writes the two scripts and lists them: p8.lua (data
    # tables + the compat shim, 61% of what it used to put in main.lua) then
    # main.lua, the cart's own code. All this adds is a third name.
    if "p8.lua" not in summary["files"]:
        raise SystemExit("%s: the importer wrote no p8.lua -- re-vendor "
                         "(make vendor-p8-import)" % lid)

    snippet = os.path.join(PERF_DIR, lid + ".lua")
    has_perf = os.path.isfile(snippet)
    if has_perf:
        with open(snippet, "r", encoding="utf-8") as f:
            body = f.read()
        with open(os.path.join(out_dir, PERF_NAME), "w",
                  encoding="utf-8", newline="\n") as f:
            f.write((GUARD_HEAD % lid) + _indent(body) + GUARD_TAIL)
        _list_source(out_dir, PERF_NAME)

    # MERGE, never overwrite: config.json is the kid's tuning surface and a
    # regenerate must not throw away a value somebody set on a board.
    cfg_path = os.path.join(out_dir, "config.json")
    cfg = {}
    if os.path.isfile(cfg_path):
        try:
            with open(cfg_path, "r", encoding="utf-8") as f:
                cfg = json.load(f)
        except Exception:                    # noqa: BLE001 -- a broken one is replaced
            cfg = {}
    # No snippet, no key: a `perf` row the cart does nothing with would be a
    # knob that lies, which is the whole failure this file exists to undo.
    if has_perf:
        cfg.setdefault("perf", 0)
    if cfg or os.path.isfile(cfg_path):
        with open(cfg_path, "w", encoding="utf-8", newline="\n") as f:
            json.dump(cfg, f, indent=2, sort_keys=True)
            f.write("\n")
    return out_dir, summary["title"], has_perf


def main(argv):
    args = [a for a in argv[1:] if not a.startswith("--")]
    dest = DEST
    for i, a in enumerate(argv):
        if a == "--dest" and i + 1 < len(argv):
            dest = argv[i + 1]
            args = [x for x in args if x != dest]
    lids = args or list(CORPUS)
    n_perf = 0
    for lid in lids:
        out_dir, title, has_perf = build(lid, dest=dest)
        n_perf += 1 if has_perf else 0
        print("%-26s -> %-34s %s  (%s)"
              % (lid, os.path.relpath(out_dir, ROOT),
                 "perf" if has_perf else "    ", title))
    print("\n%d carts, %d with a `perf` toggle (0 in each): flip it in the "
          "Editor's Config tab, or edit config.json, to measure."
          % (len(lids), n_perf))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
