#!/usr/bin/env python3
"""Generate the device's embedded fallback carts from `system_carts/`.

The MicroPython firmware does NOT ship the `system_carts/` folder; it seeds the
built-in carts onto SD on first boot from an embedded `CARTS` list and falls
back to it when SD is unavailable. That list used to be ~1800 lines of cart
sources/sprite-sheets hand-copied into `moy_runtime.py` and pinned by a parity
test -- a duplication that drifted (stale art, wrong colorkey) and made every
cart edit a two-place chore.

This script makes `system_carts/` the single source of truth: `build.sh` runs it
to emit `modules/carts_data.py` (gitignored, frozen into the firmware), and
`moy_runtime` just does `from carts_data import CARTS`. Edit `system_carts/`;
the device follows automatically.

Pure stdlib so it runs under any Python the build has.

  build_carts(dir) -> list[dict]   the CARTS structure (what gets frozen)
  render_module(carts) -> str      a freezable carts_data.py source
  as_module(dir) -> ModuleType     an in-memory carts_data (for host tests)
  main(argv)                       CLI: write the module (or stdout)
"""

import json
import os
import sys

# Launcher order on the device. Adding a system cart means adding it here (this
# tiny ordered list is the only thing still maintained by hand -- vs. the ~1800
# lines of duplicated cart bodies it replaces).
CART_ORDER = [
    "moy_night",
    "wallpaper_space",
    "ocean",
    "sakura",
    "star_catcher",
    "pet",
    "tiny_runner",
    "platformer",
    "scroll_demo",
    "battle_city",
    "tap_red",
    "tap_game",
    "beeper",
    "letter_blitz",
    "wifi",
]


def _read(path):
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def build_carts(system_carts_dir):
    """Read each system cart and build its embedded entry (title/type/src/
    sprites?/sounds?/canvas?/permissions?/cfg/edit) -- the shape moy_runtime
    expects (and seed_builtins writes back to SD)."""
    carts = []
    for folder in CART_ORDER:
        base = os.path.join(system_carts_dir, folder + ".moy")
        man = json.loads(_read(os.path.join(base, "manifest.json")))
        cart = {
            "title": man["title"],
            "type": man.get("type", "app"),
            # cart content version (#47): seed_builtins overwrites a stale on-SD copy
            # when this is newer. Pre-versioning carts default to 0.
            "version": int(man.get("version", 0)),
            "src": _read(os.path.join(base, "main.py")),
        }
        if man.get("fps"):                 # frame pacing (#63): "fps": 60 opt-out
            cart["fps"] = int(man["fps"])
        sheet = os.path.join(base, "sprites.moygfx")
        if os.path.exists(sheet):
            cart["sprites"] = _read(sheet)
        sounds = os.path.join(base, "sounds.json")     # AudioBank, optional (#16)
        if os.path.exists(sounds):
            cart["sounds"] = json.loads(_read(sounds))
        tilemap = os.path.join(base, "map.moymap")        # TileMap blob, optional (#32)
        if os.path.exists(tilemap):
            cart["map"] = _read(tilemap)
        images_dir = os.path.join(base, "images")          # paint-image assets, optional (#63)
        if os.path.isdir(images_dir):
            images = {}
            for iname in sorted(os.listdir(images_dir)):
                if iname.endswith(".moyimg"):
                    images[iname[:-len(".moyimg")]] = _read(os.path.join(images_dir, iname))
            if images:
                cart["images"] = images
        blocks = os.path.join(base, "blocks.json")      # block source (#29), optional
        if os.path.exists(blocks):
            # carry the block program so a block-authored seed (tap_game) opens in
            # the on-device block editor, not just as compiled code.
            cart["blocks"] = json.loads(_read(blocks))
        if "canvas" in man:
            cart["canvas"] = man["canvas"]
        if "permissions" in man:
            cart["permissions"] = man["permissions"]
        cart["cfg"] = man.get("config", {})
        cart["edit"] = man.get("edit", [])
        carts.append(cart)
    return carts


def render_module(carts):
    """A freezable carts_data.py: a header + `CARTS = <repr>`. repr() of plain
    str/int/list/dict is valid, deterministic Python that MicroPython parses."""
    header = (
        '"""AUTO-GENERATED by tools/gen_device_carts.py from system_carts/.\n'
        "Do NOT edit -- the build regenerates it. Edit system_carts/ instead.\n"
        '"""\n\n'
    )
    return header + "CARTS = " + repr(carts) + "\n"


def as_module(system_carts_dir):
    """An in-memory `carts_data` module (so host tests can exec moy_runtime,
    which does `from carts_data import CARTS`, without writing a file)."""
    import types
    mod = types.ModuleType("carts_data")
    mod.CARTS = build_carts(system_carts_dir)
    return mod


def _default_system_carts():
    return os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "system_carts")


def main(argv):
    out = argv[1] if len(argv) > 1 else None
    src = argv[2] if len(argv) > 2 else _default_system_carts()
    text = render_module(build_carts(src))
    if out and out != "-":
        with open(out, "w", encoding="utf-8") as f:
            f.write(text)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
