#!/usr/bin/env python3
"""The PICO-8 corpus as ONE cart each, with the measured start behind a config toggle.

    python3 tools/gen_p8_ports.py                 # all of them, into ports/p8/
    python3 tools/gen_p8_ports.py mossmoss-17     # just these lids
    python3 tools/gen_p8_ports.py --dest /tmp/x   # somewhere else

WHY ONE CART AND NOT TWO. The corpus is two things at once: the COMPATIBILITY
set (does the importer handle this cart -- does it boot, take input, draw right)
and the PERFORMANCE set (what does a frame cost with a real scene on screen).
Those wanted different starts, so the boards grew a plain import AND a "… Perf"
twin of each, and the two drifted: by 2026-09-11 every Perf cart in `ports/p8perf`
carried `P8_VH = 128` while a fresh import carries 120, so every perf number was
measured on a viewport 8 rows taller than the one a real cart draws -- and no
two boards held the same set. One cart with a toggle cannot drift from itself.

THE TOGGLE IS `config.json`'s `perf`, which is the cart API's existing
"Make it mine" surface (`cfg(key, default)`, docs/moy_cart_api.md): 0 plays the
cart normally, 1 jumps straight into the measured scene. A kid never sees it; a
measurement session flips it in the Editor's Config tab with no re-push, and
`host_app._SEED_PRESERVE` keeps the value across a re-seed. 0/1 rather than
true/false because that is what the shipped carts already use
(`brick_siege_lua.moy/config.json`) and what `cfg` types cleanly -- moy_lua.c's
`l_cfg` converts a whole-string number to a Lua number, so `cfg("perf", 0) ~= 0`
is the guard on every tier.

THE CARTS ARE NOT IN THIS REPO and must not be: they are their authors' work,
several under licences that forbid redistribution (ports/README.md). What IS
committed is the recipe -- `ports/p8/perf/<lid>.lua`, our own ~10 lines per cart
naming the scene to start in and why. The cart bytes come from moy-spec's
`conformance/p8_corpus.json` links, cached by its `fetch_p8_corpus.py` in
~/.cache/moy/p8, which is what moy-spec CI already does.
"""

import json
import os
import sys

_THIS = os.path.dirname(os.path.abspath(__file__))
if _THIS not in sys.path:
    sys.path.insert(0, _THIS)

from import_p8 import import_p8                                # noqa: E402

ROOT = os.path.dirname(_THIS)
PERF_DIR = os.path.join(ROOT, "ports", "p8", "perf")
DEST = os.path.join(ROOT, "ports", "p8")
CORPUS = os.path.join(os.path.expanduser("~"), ".cache", "moy", "p8")

# The guard, and the comment a reader of the generated cart needs -- the wrapper
# is appended to somebody else's Lua, so it says what it is where it lands.
GUARD_HEAD = """

-- ---------------------------------------------------------------------------
-- PERF START (generated by tools/gen_p8_ports.py from ports/p8/perf/%s.lua).
-- config.json's `perf`: 0 plays this cart from its own title screen, 1 starts
-- it in the scene the perf ledger (#66) measures. Everything below runs only
-- under 1, and touches nothing when it is 0.
-- ---------------------------------------------------------------------------
if cfg("perf", 0) ~= 0 then
"""
GUARD_TAIL = "end\n"


def _indent(body):
    """The snippet, one level in -- it is inside an `if` now."""
    out = []
    for line in body.splitlines():
        out.append(("  " + line) if line.strip() else line)
    return "\n".join(out).rstrip("\n") + "\n"


def build(lid, corpus=CORPUS, dest=DEST):
    """One `<dest>/<lid>.moy` from the cached cart + this lid's perf snippet."""
    src = os.path.join(corpus, lid + ".p8.png")
    if not os.path.isfile(src):
        raise SystemExit(
            "no cached cart for %s at %s -- fetch the corpus first:\n"
            "  python3 ../moy-spec/conformance/fetch_p8_corpus.py" % (lid, src))
    out_dir = os.path.join(dest, lid + ".moy")
    summary = import_p8(src, out_dir)

    snippet = os.path.join(PERF_DIR, lid + ".lua")
    with open(snippet, "r", encoding="utf-8") as f:
        body = f.read()
    main = os.path.join(out_dir, "main.lua")
    with open(main, "r", encoding="utf-8") as f:
        cart = f.read()
    with open(main, "w", encoding="utf-8", newline="\n") as f:
        f.write(cart.rstrip("\n") + "\n"
                + (GUARD_HEAD % lid) + _indent(body) + GUARD_TAIL)

    # MERGE, never overwrite: config.json is the kid's tuning surface and a
    # regenerate must not throw away a value somebody set on a board.
    cfg_path = os.path.join(out_dir, "config.json")
    cfg = {}
    if os.path.isfile(cfg_path):
        try:
            with open(cfg_path, "r", encoding="utf-8") as f:
                cfg = json.load(f)
        except Exception:                    # noqa: BLE001 -- a broken one is replaced
            cfg = {}
    cfg.setdefault("perf", 0)
    with open(cfg_path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(cfg, f, indent=2, sort_keys=True)
        f.write("\n")
    return out_dir, summary["title"]


def main(argv):
    args = [a for a in argv[1:] if not a.startswith("--")]
    dest = DEST
    for i, a in enumerate(argv):
        if a == "--dest" and i + 1 < len(argv):
            dest = argv[i + 1]
            args = [x for x in args if x != dest]
    lids = args or sorted(
        n[:-len(".lua")] for n in os.listdir(PERF_DIR) if n.endswith(".lua"))
    for lid in lids:
        out_dir, title = build(lid, dest=dest)
        print("%-26s -> %s  (%s)" % (lid, os.path.relpath(out_dir, ROOT), title))
    print("\n%d carts. `perf` is 0 in each: flip it in the Editor's Config tab "
          "(or edit config.json) to measure." % len(lids))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
