#!/usr/bin/env python3
"""Mirror the repo's GitHub issues into docs/issues/ as flat Markdown.

Writes one file per issue into docs/issues/open/ or docs/issues/closed/
(named NNNN-slug.md) plus an INDEX.md, so issue numbers referenced in
commits, docs, and conversation can be resolved without hitting the network.

Both folders are wiped and rewritten every run, so an issue that changed
state (or title/body) never leaves a stale copy behind.

Requires the `gh` CLI, authenticated (`gh auth status`).

Usage:
    python tools/sync_issues.py                 # refresh docs/issues/
    python tools/sync_issues.py --no-comments   # bodies only (1 API call)
    python tools/sync_issues.py --repo owner/name --out docs/issues
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

LIST_FIELDS = "number,title,state,labels,author,createdAt,updatedAt,closedAt,url,body"


def gh(args: list[str]) -> str:
    """Run a gh command and return stdout, or exit with a clear error."""
    try:
        out = subprocess.run(
            ["gh", *args], check=True, capture_output=True, text=True
        )
    except FileNotFoundError:
        sys.exit("error: `gh` CLI not found. Install GitHub CLI and run `gh auth login`.")
    except subprocess.CalledProcessError as exc:
        sys.exit(f"error: `gh {' '.join(args)}` failed:\n{exc.stderr.strip()}")
    return out.stdout


def repo_slug(explicit: str | None) -> str:
    if explicit:
        return explicit
    out = gh(["repo", "view", "--json", "nameWithOwner", "-q", ".nameWithOwner"]).strip()
    return out or "moybyte-org/moybyte"


def slugify(title: str, limit: int = 50) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
    return (slug[:limit].rstrip("-")) or "issue"


def short_date(iso: str | None) -> str:
    return (iso or "")[:10] or "—"


def issue_markdown(issue: dict, comments: list[dict]) -> str:
    labels = ", ".join(lbl["name"] for lbl in issue.get("labels", [])) or "—"
    author = (issue.get("author") or {}).get("login", "—")
    lines = [
        f"# #{issue['number']} — {issue['title']}",
        "",
        f"- **State:** {issue['state']}",
        f"- **Labels:** {labels}",
        f"- **Author:** {author}",
        f"- **Created:** {short_date(issue.get('createdAt'))}",
        f"- **Updated:** {short_date(issue.get('updatedAt'))}",
    ]
    if issue.get("closedAt"):
        lines.append(f"- **Closed:** {short_date(issue.get('closedAt'))}")
    lines += [
        f"- **URL:** {issue.get('url', '')}",
        "",
        "## Description",
        "",
        (issue.get("body") or "_No description._").strip(),
        "",
    ]
    if comments:
        lines.append(f"## Comments ({len(comments)})")
        lines.append("")
        for c in comments:
            who = (c.get("author") or {}).get("login", "—")
            when = short_date(c.get("createdAt"))
            lines.append(f"### {who} — {when}")
            lines.append("")
            lines.append((c.get("body") or "").strip())
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write_index(out: Path, slug: str, issues: list[dict]) -> None:
    def rows(state: str) -> list[str]:
        sub = sorted(
            (i for i in issues if i["state"].upper() == state),
            key=lambda i: i["number"],
            reverse=True,
        )
        folder = "open" if state == "OPEN" else "closed"
        out_rows = []
        for i in sub:
            labels = ", ".join(lbl["name"] for lbl in i.get("labels", [])) or ""
            fname = f"{folder}/{i['number']:04d}-{slugify(i['title'])}.md"
            suffix = f" — _{labels}_" if labels else ""
            out_rows.append(f"- [#{i['number']} {i['title']}]({fname}){suffix}")
        return out_rows

    open_rows = rows("OPEN")
    closed_rows = rows("CLOSED")
    body = [
        f"# Issue mirror — {slug}",
        "",
        "_Auto-generated by `tools/sync_issues.py`. Do not edit by hand — run "
        "`make sync-issues` to refresh._",
        "",
        f"{len(open_rows)} open · {len(closed_rows)} closed · {len(issues)} total",
        "",
        f"## Open ({len(open_rows)})",
        "",
        *(open_rows or ["_none_"]),
        "",
        f"## Closed ({len(closed_rows)})",
        "",
        *(closed_rows or ["_none_"]),
        "",
    ]
    (out / "INDEX.md").write_text("\n".join(body), encoding="utf-8")


# ---------------------------------------------------------------------------
# STATUS.md — the generated "at a glance" matrix (see docs/issue_taxonomy.md).
# Rows = open issues grouped by area:*, columns = the maturity:* ladder rung +
# tracker/status flags. Derived purely from labels so it can never go stale;
# GitHub's own label filters remain the committed source of truth.
# ---------------------------------------------------------------------------

# The readiness ladder, ordered idea → hardened (shipped == closed, implicit).
MATURITY = {
    "idea":      (1, "①", "idea — unspecced concept"),
    "spec":      (2, "②", "spec — design settled, not built"),
    "prototype": (3, "③", "prototype — partial / rough / spike"),
    "host":      (4, "④", "host — works in the host sim, not device-verified"),
    "device":    (5, "⑤", "device — verified on real hardware"),
    "hardened":  (6, "⑥", "hardened — on-glass verified, in the shipped seed"),
}
MATURITY_UNKNOWN = (0, "·", "unclassified")

# The build-requirement axis: what a machine needs to advance the work.
BUILD = {
    "host":         ("🟢", "host — buildable + testable here, no device"),
    "host-partial": ("🟡", "host-partial — host leg workable, device leg blocked"),
    "device":       ("🔴", "device — needs firmware / native C / on-glass / radio"),
}

AREA_ORDER = [
    "launcher", "editor", "wm", "player", "blocks", "carts", "apps",
    "audio", "input", "multiplayer", "webview", "ota", "perf",
    "p4", "tdeck", "hardware", "ai", "tooling", "brand", "docs",
]


def _split_labels(issue: dict) -> tuple[list[str], str | None, list[str], bool, str | None]:
    """Return (areas, maturity_key, statuses, is_tracker, build_key) from labels."""
    areas, statuses, maturity, tracker, build = [], [], None, False, None
    for lbl in issue.get("labels", []):
        name = lbl["name"]
        if name.startswith("area:"):
            areas.append(name[len("area:"):])
        elif name.startswith("maturity:"):
            maturity = name[len("maturity:"):]
        elif name.startswith("status:"):
            statuses.append(name[len("status:"):])
        elif name.startswith("build:"):
            build = name[len("build:"):]
        elif name == "tracker":
            tracker = True
    return areas, maturity, statuses, tracker, build


def _mat(maturity: str | None) -> tuple[int, str, str]:
    return MATURITY.get(maturity or "", MATURITY_UNKNOWN)


def _issue_cell(issue: dict, maturity: str | None, statuses: list[str],
                tracker: bool, build: str | None = None) -> str:
    order, sym, _ = _mat(maturity)
    flags = ""
    if build in BUILD:
        flags += " " + BUILD[build][0]
    if tracker:
        flags += " ⏳"
    for s in statuses:
        flags += f" `{s}`"
    title = issue["title"]
    return (f"| {sym} {maturity or '—'} | [#{issue['number']}]({issue.get('url','')}) "
            f"| {title}{flags} |")


def write_status(out: Path, slug: str, issues: list[dict]) -> None:
    open_issues = [i for i in issues if i["state"].upper() == "OPEN"]

    # Bucket by area (an issue can appear under several areas).
    by_area: dict[str, list[dict]] = {}
    unclassified: list[dict] = []
    trackers: list[dict] = []
    for i in open_issues:
        areas, maturity, statuses, tracker, build = _split_labels(i)
        i["_maturity"], i["_statuses"], i["_tracker"] = maturity, statuses, tracker
        i["_build"] = build
        if tracker:
            trackers.append(i)
        if not areas:
            unclassified.append(i)
        for a in areas:
            by_area.setdefault(a, []).append(i)

    ordered_areas = [a for a in AREA_ORDER if a in by_area]
    ordered_areas += sorted(a for a in by_area if a not in AREA_ORDER)

    body: list[str] = [
        f"# Status matrix — {slug}",
        "",
        "_Auto-generated by `tools/sync_issues.py` from issue labels. Do not edit "
        "by hand — run `make sync-issues` to refresh. GitHub's label filters are "
        "the source of truth; this is a convenience view. See "
        "`docs/issue_taxonomy.md` for the label scheme._",
        "",
        "**Readiness ladder** (the `maturity:*` axis):",
        "",
    ]
    for key in MATURITY:
        order, sym, desc = MATURITY[key]
        body.append(f"- {sym} **{key}** — {desc.split('—',1)[1].strip()}")
    body += [
        "",
        "**Build requirement** (the `build:*` axis — what it takes to advance the work):",
        "",
    ]
    for key, (mark, desc) in BUILD.items():
        body.append(f"- {mark} **{key}** — {desc.split('—',1)[1].strip()}")
    body += [
        "",
        "⏳ = living **tracker** issue (continuously updated, not a one-shot task). "
        "Status flags: `blocked`, `pending-decision`, `pending-testing`.",
        "",
        "---",
        "",
    ]

    # Per-area sections, each sorted most-mature first.
    body.append("## By area")
    body.append("")
    for area in ordered_areas:
        # Umbrella tracker first, then most-mature first.
        items = sorted(by_area[area],
                       key=lambda i: (0 if i["_tracker"] else 1,
                                      -_mat(i["_maturity"])[0], i["number"]))
        body += [f"### area:{area} ({len(items)})", "",
                 "| Maturity | Issue | What |", "|---|---|---|"]
        for i in items:
            body.append(_issue_cell(i, i["_maturity"], i["_statuses"],
                                    i["_tracker"], i["_build"]))
        body.append("")

    if unclassified:
        body += ["### unclassified ({})".format(len(unclassified)), "",
                 "| Maturity | Issue | What |", "|---|---|---|"]
        for i in unclassified:
            body.append(_issue_cell(i, i["_maturity"], i["_statuses"],
                                    i["_tracker"], i["_build"]))
        body.append("")

    # "Ready to work" — actionable = not blocked, not awaiting a decision.
    ready = [i for i in open_issues
             if not i["_tracker"]
             and "blocked" not in i["_statuses"]
             and "pending-decision" not in i["_statuses"]]
    ready.sort(key=lambda i: (-_mat(i["_maturity"])[0], i["number"]))
    body += ["---", "", f"## Ready to work ({len(ready)})", "",
             "_Open, non-tracker issues that are neither `blocked` nor "
             "`pending-decision` — sorted most-mature first (closest to shipping "
             "at the top)._", "",
             "| Maturity | Issue | What |", "|---|---|---|"]
    for i in ready:
        body.append(_issue_cell(i, i["_maturity"], i["_statuses"],
                                i["_tracker"], i["_build"]))
    body.append("")

    # "Buildable on host" — pick-up-today on a host-only box (no device/firmware).
    buildable = [i for i in open_issues
                 if not i["_tracker"] and i["_build"] in ("host", "host-partial")]
    buildable.sort(key=lambda i: (0 if i["_build"] == "host" else 1,
                                  -_mat(i["_maturity"])[0], i["number"]))
    body += ["---", "", f"## Buildable on host ({len(buildable)})", "",
             "_Open, non-tracker issues tagged `build:host` (🟢) or "
             "`build:host-partial` (🟡) — workable on a host-only dev box with no "
             "firmware build, C toolchain, or device to flash. Sorted host-first, "
             "then most-mature._", "",
             "| Maturity | Issue | What |", "|---|---|---|"]
    for i in buildable:
        body.append(_issue_cell(i, i["_maturity"], i["_statuses"],
                                i["_tracker"], i["_build"]))
    body.append("")

    # Living trackers roll-up.
    trackers.sort(key=lambda i: i["number"])
    body += ["---", "", f"## Living trackers ({len(trackers)})", "",
             "_Persistent, continuously-updated issues — read these for current "
             "state rather than treating them as tasks to close._", ""]
    for i in trackers:
        areas, _, _, _, _ = _split_labels(i)
        atags = " ".join(f"`{a}`" for a in areas)
        body.append(f"- ⏳ [#{i['number']} {i['title']}]({i.get('url','')}) — {atags}")
    body.append("")

    (out / "STATUS.md").write_text("\n".join(body), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--repo", help="owner/name (default: current repo)")
    ap.add_argument("--out", default="docs/issues", help="output dir (default docs/issues)")
    ap.add_argument("--no-comments", action="store_true", help="skip fetching comments")
    args = ap.parse_args()

    slug = repo_slug(args.repo)
    out = Path(args.out)
    print(f"Syncing issues from {slug} → {out}/", file=sys.stderr)

    issues = json.loads(
        gh(["issue", "list", "--repo", slug, "--state", "all", "--limit", "1000",
            "--json", LIST_FIELDS])
    )

    for folder in ("open", "closed"):
        d = out / folder
        if d.exists():
            shutil.rmtree(d)
        d.mkdir(parents=True, exist_ok=True)

    for idx, issue in enumerate(issues, 1):
        num = issue["number"]
        comments: list[dict] = []
        if not args.no_comments:
            data = json.loads(
                gh(["issue", "view", str(num), "--repo", slug, "--json", "comments"])
            )
            comments = data.get("comments", [])
        folder = "open" if issue["state"].upper() == "OPEN" else "closed"
        fname = out / folder / f"{num:04d}-{slugify(issue['title'])}.md"
        fname.write_text(issue_markdown(issue, comments), encoding="utf-8")
        print(f"  [{idx}/{len(issues)}] #{num} → {folder}/{fname.name}", file=sys.stderr)

    write_index(out, slug, issues)
    write_status(out, slug, issues)
    n_open = sum(1 for i in issues if i["state"].upper() == "OPEN")
    print(f"Done: {n_open} open, {len(issues) - n_open} closed, {len(issues)} total.",
          file=sys.stderr)


if __name__ == "__main__":
    main()
