#!/usr/bin/env python3
"""Mirror the repo's GitHub issues into docs/issues/ as flat Markdown.

Writes one file per issue into docs/issues/open/ or docs/issues/closed/
(named NNNN-slug.md) plus an INDEX.md, so issue numbers referenced in
commits, docs, and conversation can be resolved without hitting the network.

Both folders are wiped and rewritten every run, so an issue that changed
state (or title/body) never leaves a stale copy behind.

Requires the `gh` CLI, authenticated (`gh auth status`).

Usage:
    python tools/sync_issues.py                 # refresh docs/issues/
    python tools/sync_issues.py --no-comments   # bodies only (1 API call)
    python tools/sync_issues.py --repo owner/name --out docs/issues
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

LIST_FIELDS = "number,title,state,labels,author,createdAt,updatedAt,closedAt,url,body"


def gh(args: list[str]) -> str:
    """Run a gh command and return stdout, or exit with a clear error."""
    try:
        out = subprocess.run(
            ["gh", *args], check=True, capture_output=True, text=True
        )
    except FileNotFoundError:
        sys.exit("error: `gh` CLI not found. Install GitHub CLI and run `gh auth login`.")
    except subprocess.CalledProcessError as exc:
        sys.exit(f"error: `gh {' '.join(args)}` failed:\n{exc.stderr.strip()}")
    return out.stdout


def repo_slug(explicit: str | None) -> str:
    if explicit:
        return explicit
    out = gh(["repo", "view", "--json", "nameWithOwner", "-q", ".nameWithOwner"]).strip()
    return out or "nikola-j/moybyte"


def slugify(title: str, limit: int = 50) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
    return (slug[:limit].rstrip("-")) or "issue"


def short_date(iso: str | None) -> str:
    return (iso or "")[:10] or "—"


def issue_markdown(issue: dict, comments: list[dict]) -> str:
    labels = ", ".join(lbl["name"] for lbl in issue.get("labels", [])) or "—"
    author = (issue.get("author") or {}).get("login", "—")
    lines = [
        f"# #{issue['number']} — {issue['title']}",
        "",
        f"- **State:** {issue['state']}",
        f"- **Labels:** {labels}",
        f"- **Author:** {author}",
        f"- **Created:** {short_date(issue.get('createdAt'))}",
        f"- **Updated:** {short_date(issue.get('updatedAt'))}",
    ]
    if issue.get("closedAt"):
        lines.append(f"- **Closed:** {short_date(issue.get('closedAt'))}")
    lines += [
        f"- **URL:** {issue.get('url', '')}",
        "",
        "## Description",
        "",
        (issue.get("body") or "_No description._").strip(),
        "",
    ]
    if comments:
        lines.append(f"## Comments ({len(comments)})")
        lines.append("")
        for c in comments:
            who = (c.get("author") or {}).get("login", "—")
            when = short_date(c.get("createdAt"))
            lines.append(f"### {who} — {when}")
            lines.append("")
            lines.append((c.get("body") or "").strip())
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write_index(out: Path, slug: str, issues: list[dict]) -> None:
    def rows(state: str) -> list[str]:
        sub = sorted(
            (i for i in issues if i["state"].upper() == state),
            key=lambda i: i["number"],
            reverse=True,
        )
        folder = "open" if state == "OPEN" else "closed"
        out_rows = []
        for i in sub:
            labels = ", ".join(lbl["name"] for lbl in i.get("labels", [])) or ""
            fname = f"{folder}/{i['number']:04d}-{slugify(i['title'])}.md"
            suffix = f" — _{labels}_" if labels else ""
            out_rows.append(f"- [#{i['number']} {i['title']}]({fname}){suffix}")
        return out_rows

    open_rows = rows("OPEN")
    closed_rows = rows("CLOSED")
    body = [
        f"# Issue mirror — {slug}",
        "",
        "_Auto-generated by `tools/sync_issues.py`. Do not edit by hand — run "
        "`make sync-issues` to refresh._",
        "",
        f"{len(open_rows)} open · {len(closed_rows)} closed · {len(issues)} total",
        "",
        f"## Open ({len(open_rows)})",
        "",
        *(open_rows or ["_none_"]),
        "",
        f"## Closed ({len(closed_rows)})",
        "",
        *(closed_rows or ["_none_"]),
        "",
    ]
    (out / "INDEX.md").write_text("\n".join(body), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--repo", help="owner/name (default: current repo)")
    ap.add_argument("--out", default="docs/issues", help="output dir (default docs/issues)")
    ap.add_argument("--no-comments", action="store_true", help="skip fetching comments")
    args = ap.parse_args()

    slug = repo_slug(args.repo)
    out = Path(args.out)
    print(f"Syncing issues from {slug} → {out}/", file=sys.stderr)

    issues = json.loads(
        gh(["issue", "list", "--repo", slug, "--state", "all", "--limit", "1000",
            "--json", LIST_FIELDS])
    )

    for folder in ("open", "closed"):
        d = out / folder
        if d.exists():
            shutil.rmtree(d)
        d.mkdir(parents=True, exist_ok=True)

    for idx, issue in enumerate(issues, 1):
        num = issue["number"]
        comments: list[dict] = []
        if not args.no_comments:
            data = json.loads(
                gh(["issue", "view", str(num), "--repo", slug, "--json", "comments"])
            )
            comments = data.get("comments", [])
        folder = "open" if issue["state"].upper() == "OPEN" else "closed"
        fname = out / folder / f"{num:04d}-{slugify(issue['title'])}.md"
        fname.write_text(issue_markdown(issue, comments), encoding="utf-8")
        print(f"  [{idx}/{len(issues)}] #{num} → {folder}/{fname.name}", file=sys.stderr)

    write_index(out, slug, issues)
    n_open = sum(1 for i in issues if i["state"].upper() == "OPEN")
    print(f"Done: {n_open} open, {len(issues) - n_open} closed, {len(issues)} total.",
          file=sys.stderr)


if __name__ == "__main__":
    main()
